import propsJson from "../generated/props.json";

interface PropRow {
  name: string;
  type: string;
  required: boolean;
  description: string;
  default?: string;
}
interface PropsDoc {
  component: string;
  package: string;
  extends: string[];
  props: PropRow[];
}

const all = propsJson as Record<string, PropsDoc>;

export function propsFor(component: string | null): PropsDoc | undefined {
  return component ? all[component] : undefined;
}

/** The props table, generated by `npm run props` from the component's TypeScript interface. */
export function PropsTable({ component }: { component: string | null }) {
  const doc = propsFor(component);
  if (!doc) return null;
  return (
    <section className="flex flex-col gap-3" aria-labelledby="props-heading">
      <h2 id="props-heading" className="m-0 text-lg">
        Props
      </h2>
      <div className="overflow-x-auto">
        <table className="w-full border-collapse text-left text-sm">
          <thead>
            <tr className="border-b border-line text-muted">
              <th className="py-2 pr-4 font-normal">Name</th>
              <th className="py-2 pr-4 font-normal">Type</th>
              <th className="py-2 pr-4 font-normal">Default</th>
              <th className="py-2 font-normal">Description</th>
            </tr>
          </thead>
          <tbody>
            {doc.props.map((p) => (
              <tr key={p.name} className="border-b border-line align-top">
                <td className="py-2 pr-4 text-ink">
                  {p.name}
                  {p.required ? <span className="text-danger"> *</span> : null}
                </td>
                <td className="py-2 pr-4 text-muted">{p.type}</td>
                <td className="py-2 pr-4 text-muted">{p.default ?? ""}</td>
                <td className="py-2 text-muted">{p.description}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      {doc.extends.length > 0 ? (
        <p className="m-0 text-sm text-muted">
          Also accepts the props of {doc.extends.map((e) => `\`${e}\``).join(", ")}.
        </p>
      ) : null}
    </section>
  );
}
