import { readFileSync, writeFileSync } from "node:fs";
import { displayWeight, hexPalette, readThemeBlocks, textSizePx } from "./colors.ts";

const root = new URL("..", import.meta.url).pathname;
const blocks = readThemeBlocks(`${root}theme.css`);
const css = readFileSync(`${root}theme.css`, "utf8");

const tokens = {
  $comment: "Generated by `npm run build:email-tokens` from theme.css. Do not edit.",
  light: hexPalette(blocks.light),
  dark: hexPalette(blocks.dark),
  fontFamily: "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace",
  text: {
    body: textSizePx(css, "body"),
    display: { ...textSizePx(css, "display"), weight: displayWeight(css) },
  },
  radius: "4px",
  maxWidth: "560px",
};

writeFileSync(`${root}email/tokens.json`, `${JSON.stringify(tokens, null, 2)}\n`);
console.log("wrote email/tokens.json");
