import { writeFileSync } from "node:fs";
import { hexPalette, readThemeOklch } from "./colors.ts";

const root = new URL("..", import.meta.url).pathname;
const { light, dark } = readThemeOklch(`${root}theme.css`);

const tokens = {
  $comment: "Generated by `npm run build:email-tokens` from theme.css. Do not edit.",
  light: hexPalette(light),
  dark: hexPalette(dark),
  fontFamily:
    "ui-monospace, SFMono-Regular, Menlo, Consolas, 'Liberation Mono', monospace",
  radius: "4px",
  maxWidth: "560px",
};

writeFileSync(`${root}email/tokens.json`, `${JSON.stringify(tokens, null, 2)}\n`);
console.log("wrote email/tokens.json");
