// Builds docs/reference.md: one entry per export of every public entry point, from the source's types and doc comments.
import { join } from "node:path";
import ts from "typescript";

const root = join(import.meta.dirname, "..");

/** The public entry points: the import path and the source file that defines its exports. */
export const ENTRIES = [
  { path: "@teb-ooo/ui", file: "src/index.ts" },
  { path: "@teb-ooo/ui/cmdk", file: "src/cmdk/index.ts" },
  { path: "@teb-ooo/ui/editor", file: "src/editor/index.ts" },
  { path: "@teb-ooo/ui/markdown", file: "src/markdown/index.ts" },
] as const;

export interface ExportEntry {
  name: string;
  /** component, hook, function or constant for values; type for types. */
  kind: "component" | "hook" | "function" | "constant" | "type";
  summary: string;
  props: { name: string; type: string; required: boolean; default: string; description: string }[];
  extendsTypes: string[];
}

const flat = (s: string) => s.replace(/\s+/g, " ").trim();

function program(): ts.Program {
  const cfg = ts.readConfigFile(join(root, "tsconfig.json"), ts.sys.readFile);
  const parsed = ts.parseJsonConfigFileContent(cfg.config, ts.sys, root);
  return ts.createProgram(
    ENTRIES.map((e) => join(root, e.file)),
    { ...parsed.options, noEmit: true },
  );
}

/** Every export of every entry point, in a stable order: values by name, then types by name. */
export function collectExports(): { path: string; entries: ExportEntry[] }[] {
  const prog = program();
  const checker = prog.getTypeChecker();
  return ENTRIES.map(({ path, file }) => {
    const sf = prog.getSourceFile(join(root, file));
    if (!sf) throw new Error(`cannot read ${file}`);
    const mod = checker.getSymbolAtLocation(sf);
    if (!mod) throw new Error(`${file} has no exports`);
    const symbols = checker.getExportsOfModule(mod).map((s) => (s.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(s) : s));
    const byName = new Map(symbols.map((s) => [s.getName(), s]));
    const entries: ExportEntry[] = symbols.map((s) => {
      const name = s.getName();
      const isValue = (s.flags & ts.SymbolFlags.Value) !== 0;
      const propsSym = byName.get(`${name}Props`);
      const kind: ExportEntry["kind"] = !isValue
        ? "type"
        : name.startsWith("use")
          ? "hook"
          : /^[A-Z]/u.test(name) && (propsSym !== undefined || (s.flags & (ts.SymbolFlags.Function | ts.SymbolFlags.Variable)) !== 0 && /^[A-Z][a-z]/u.test(name) && !/^[A-Z_]+$/u.test(name))
            ? (s.flags & ts.SymbolFlags.Function) !== 0 || propsSym !== undefined
              ? "component"
              : "constant"
            : (s.flags & ts.SymbolFlags.Function) !== 0
              ? "function"
              : "constant";
      const summary = flat(ts.displayPartsToString(s.getDocumentationComment(checker)));
      const decl = isValue ? propsSym?.declarations?.find(ts.isInterfaceDeclaration) : undefined;
      const props = (decl?.members.filter(ts.isPropertySignature) ?? []).map((m) => {
        const def = ts.getJSDocTags(m).find((t) => t.tagName.text === "default");
        const sig = checker.getSymbolAtLocation(m.name);
        return {
          name: m.name.getText(),
          type: flat(m.type?.getText() ?? "unknown"),
          required: m.questionToken === undefined,
          default: def?.comment ? flat(ts.getTextOfJSDocComment(def.comment) ?? "") : "",
          description: flat(ts.displayPartsToString(sig?.getDocumentationComment(checker) ?? [])),
        };
      });
      const extendsTypes = (decl?.heritageClauses ?? []).flatMap((h) => h.types.map((t) => flat(t.getText())));
      return { name, kind, summary, props, extendsTypes };
    });
    const order = (e: ExportEntry) => (e.kind === "type" ? 1 : 0);
    entries.sort((a, b) => order(a) - order(b) || a.name.localeCompare(b.name));
    return { path, entries };
  });
}

/** A `*Props` type documented under its component is not listed again. */
function listed(entry: ExportEntry, all: ExportEntry[]): boolean {
  if (entry.kind !== "type" || !entry.name.endsWith("Props")) return true;
  const owner = all.find((e) => e.name === entry.name.slice(0, -"Props".length));
  return !(owner && owner.kind !== "type");
}

export function buildReference(): string {
  const out: string[] = [
    "# Reference",
    "",
    "Generated by `npm run build:reference` from the source's types and doc comments; do not edit it. Every export of every entry point has one entry. The guidance on using them together is in `components.md` and `best-practices.md`; the running examples are in the gallery (https://ui.teb.ooo).",
    "",
  ];
  for (const { path, entries } of collectExports()) {
    out.push(`## ${path}`, "");
    const values = entries.filter((e) => e.kind !== "type");
    for (const e of values) {
      out.push(`### ${e.name}`, "", `${e.kind}: \`import { ${e.name} } from "${path}"\``, "");
      if (e.summary) out.push(e.summary, "");
      if (e.extendsTypes.length > 0) out.push(`Also accepts the props of ${e.extendsTypes.map((t) => `\`${t}\``).join(", ")}.`, "");
      for (const p of e.props) {
        out.push(`- \`${p.name}${p.required ? "" : "?"}\`: \`${p.type}\`${p.default ? `, default ${p.default}` : ""}${p.description ? `. ${p.description}` : ""}`);
      }
      if (e.props.length > 0) out.push("");
    }
    const types = entries.filter((e) => e.kind === "type" && listed(e, entries));
    if (types.length > 0) {
      out.push("### Types", "");
      for (const t of types) out.push(`- \`${t.name}\`${t.summary ? `: ${t.summary}` : ""}`);
      out.push("");
    }
  }
  return out.join("\n");
}
